name: 'data_knows_all'
version: '1.0.0'
config-version: 2

dbt-cloud:
    project-id: 298058

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  data_knows_all:
    +enabled: true
    +database: staging

models:
  data_knows_all:
    marts:
      deadpool:
        +enabled: true
        +materialized: view
        +database: deadpool
      hubspot:
          +enabled: true
          +materialized: view
          +database: analytics
      notion:
          +enabled: true
          +materialized: view
          +database: analytics
      pivots:
          +enabled: true
          +materialized: view
          +database: analytics
      quickbooks:
          +enabled: true
          +materialized: view
          +database: analytics
    staging:
      deadpool:
        +enabled: true
        +materialized: view
        +database: staging
      hubspot:
        +enabled: true
        +materialized: view
        +database: staging
      notion:
        +enabled: true
        +materialized: view
        +database: staging
      pivots:
        +enabled: true
        +materialized: view
        +database: staging
      quickbooks:
        +enabled: true
        +materialized: view
        +database: staging
    intermediate:
      deadpool:
        +enabled: true
        +materialized: view
        +database: staging
      notion:
        +enabled: true
        +materialized: view
        +database: staging