with 

source as (

    select * from {{ source('hubspot', 'deal') }}

),

renamed as (

    select
        deal_id,
        portal_id,
        is_deleted,
        _fivetran_deleted,
        property_hs_date_entered_decisionmakerboughtin,
        property_hs_num_associated_active_deal_registrations,
        owner_id,
        property_hs_projected_amount_in_home_currency,
        property_num_associated_contacts,
        property_hs_date_exited_contractsent,
        property_hs_deal_stage_probability_shadow,
        property_days_to_close,
        property_hs_date_entered_appointmentscheduled,
        property_hs_closed_won_date,
        property_hs_date_exited_appointmentscheduled,
        property_hs_deal_stage_probability,
        property_closedate,
        property_hs_lastmodifieddate,
        property_hs_analytics_latest_source_data_2_contact,
        property_hs_date_entered_presentationscheduled,
        property_hs_acv,
        property_hs_object_source,
        property_dealtype,
        property_hs_analytics_latest_source_data_1_company,
        property_hs_date_exited_presentationscheduled,
        property_hs_analytics_source,
        property_hs_time_in_presentationscheduled,
        property_hs_is_closed_won,
        property_hs_time_in_contractsent,
        property_hs_analytics_latest_source_data_2,
        property_hs_user_ids_of_all_owners,
        property_hs_analytics_latest_source_data_1,
        property_hs_analytics_latest_source_contact,
        property_hs_priority,
        property_hs_date_exited_decisionmakerboughtin,
        property_hs_arr,
        property_hs_num_target_accounts,
        property_hs_is_open_count,
        deal_pipeline_id,
        property_hs_tcv,
        property_dealname,
        deal_pipeline_stage_id,
        property_amount,
        property_hs_time_in_closedwon,
        property_hs_createdate,
        property_hs_analytics_latest_source,
        property_hs_analytics_latest_source_timestamp,
        property_hs_analytics_latest_source_data_1_contact,
        property_hs_days_to_close_raw,
        property_hs_num_associated_deal_registrations,
        property_hs_analytics_source_data_2,
        property_hs_forecast_amount,
        property_hs_analytics_source_data_1,
        property_hs_closed_amount_in_home_currency,
        property_hs_analytics_latest_source_timestamp_contact,
        property_hs_time_in_decisionmakerboughtin,
        property_hs_time_in_appointmentscheduled,
        property_hs_is_closed,
        property_hs_updated_by_user_id,
        property_amount_in_home_currency,
        property_hs_created_by_user_id,
        property_hs_analytics_latest_source_data_2_company,
        property_hubspot_owner_assigneddate,
        property_hs_mrr,
        property_hs_num_of_associated_line_items,
        property_hs_projected_amount,
        property_hs_object_source_id,
        property_hs_analytics_latest_source_company,
        property_createdate,
        property_hs_date_entered_contractsent,
        property_hs_num_associated_deal_splits,
        property_hs_closed_amount,
        property_hs_is_deal_split,
        property_hs_closed_won_count,
        property_hs_date_entered_closedwon,
        property_hs_object_id,
        property_hs_all_owner_ids,
        property_hs_object_source_user_id,
        _fivetran_synced

    from source

)

select * from renamed
